version: "3.9"
services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    env_file:
      - .env.dev
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    extends:
      file: docker-compose.yml
      service: pgadmin
    env_file:
      - .env.dev
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
  pgadmin:
