version: "3.9"
services:
  app:
    build: .
    env_file:
      - .env.prod
    ports:
      - 3000:3000
  db:
    extends:
      file: docker-compose.yml
      service: db
    env_file:
      - .env.prod
