POST http://localhost:3000/users
content-type: application/json

{
  "username": "oleg",
  "password": "oleg"
}

###

GET http://localhost:3000/users
authorization: JWT eyJhbGciOiJIUzI1NiJ9.MTE3.nxZzHYfcAdSO5PQjVJlmxc1PeJgxc056QvLwSw18jTI